### ISSUE TITLE
MUMHED may have been stolen from HERETIC.WAD

### ISSUE THREAD

**Issue by Talon1024** [Catoptromancy/blasphemer#11]
MUMHED is the sound the ghoul's projectiles make. It may have been stolen from HERETIC.WAD.

If you open a Blasphemer IWAD build and HERETIC.WAD in SLADE, listen to MUMHED from Blasphemer, and then listen to RESPAWN from HERETIC.WAD. These two sounds are almost exactly the same.

**Comment by Catoptromancy** [comment]
The respawn sounds in both iwads seem most identical. Mumhed in blasphemer is heavily edited and pitch shifted? I dont mind replacing both. Will reuse something already in wad for now.

**Comment by GeorgePieVG** [comment]
I think the sounds from librequake attic can be used for replacements, for example [ogdth.wav](https://github.com/MissLavender-LQ/lq-attic-and-sourcefiles/blob/main/src/sounds/ogre/ogdth.wav) can replace MUMHED and [itembk2.wav](https://github.com/MissLavender-LQ/lq-attic-and-sourcefiles/blob/main/src/sounds/items/itembk2.wav) can replace RESPAWN. I haven't found any specific credits for the authors of these sounds though, it makes sense to ask MissLavender first.

**Comment by Catoptromancy** [comment]
Looks like this was just replaced in latest commit.
